services:
  mysql:
    image: mysql:8.2
    container_name: scrm_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - scrm_net

  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: scrm_pma
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
    networks:
      - scrm_net

  backend:
    depends_on:
      - mysql
    container_name: scrm_backend
    image: jhordyess/java:17-3
    volumes:
      - .:/spring-cloudinary-react-mysql:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DB_HOST=mysql:3306
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    networks:
      - scrm_net

  frontend:
    depends_on:
      - backend
    container_name: scrm_frontend
    image: jhordyess/node:18
    volumes:
      - .:/spring-cloudinary-react-mysql:cached
    environment:
      - VITE_BACKEND_URL
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - scrm_net

volumes:
  mysql-data:


networks:
  scrm_net:
    driver: bridge
